name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build .            
      - name: Run `nix build`
        run: nix develop             
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      # - name: Deploy to Cloudflare Workers with Wrangler
      #   # You may pin to the exact commit or the version.
      #   # uses: cloudflare/wrangler-action@c25aadc9657b0cdc4786c04e59a6fe92765a783b
      #   uses: cloudflare/wrangler-action@v3.14.1
      #   with:
      #     #Your Cloudflare API Token
      #     apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
      #     # Your Cloudflare Account ID
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     preCommand: nix develop
      #     command: pages deploy
      #     packageManager: bun
      #     # The version of Wrangler you'd like to use to deploy your Workers project
      #     wranglerVersion: 4.54.0 # optional
          
